# Generated by Django 3.1.4 on 2021-01-06 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название проекта')),
                ('prefix', models.CharField(max_length=150, verbose_name='Префикс')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Лидер проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название спринта')),
                ('aim', models.TextField(verbose_name='Цель спринта')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Начало спринта')),
                ('finishDate', models.DateField(blank=True, null=True, verbose_name='Окончание спринта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Спринт',
                'verbose_name_plural': 'Спринты',
                'db_table': 'Sprint',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamLimit', models.SmallIntegerField(verbose_name='Ограничение кол-ва участников')),
                ('sprintLimit', models.SmallIntegerField(verbose_name='Ограничение длительности спринта')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Настроки проекта',
                'verbose_name_plural': 'Настройки проектов',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='settings',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='projects.projectsettings', verbose_name='Настройки'),
        ),
    ]
