# Generated by Django 3.1.4 on 2021-01-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
