# Generated by Django 3.1.4 on 2020-12-14 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
                'db_table': 'Board',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название проекта')),
                ('prefix', models.CharField(max_length=150, verbose_name='Префикс')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Лидер проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamLimit', models.SmallIntegerField(verbose_name='Ограничение кол-ва участников')),
                ('sprintLimit', models.SmallIntegerField(verbose_name='Ограничение длительности спринта')),
            ],
            options={
                'verbose_name': 'Настроки проекта',
                'verbose_name_plural': 'Настройки проектов',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Лидер')),
                ('participants', models.ManyToManyField(related_name='Teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyPoints', models.SmallIntegerField(default=0, verbose_name='Story Points')),
                ('body', models.TextField(verbose_name='Тело задачи')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board', verbose_name='Доска')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'Task',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'Статус задач',
                'verbose_name_plural': 'Статусы задач',
                'db_table': 'Status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название спринта')),
                ('aim', models.TextField(verbose_name='Цель спринта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Спринт',
                'verbose_name_plural': 'Спринты',
                'db_table': 'Sprint',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.projectsettings'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Тело комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.comment', verbose_name='Родительский комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комментарии',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='board',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.team', verbose_name='Команда'),
        ),
    ]
