# Generated by Django 3.1.4 on 2020-12-14 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='finishDate',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание спринта'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Начало спринта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.projectsettings'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название спринта'),
        ),
    ]
