# Generated by Django 3.1.4 on 2021-01-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='team',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
    ]
