# Generated by Django 3.1.4 on 2020-12-14 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20201215_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='project',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='boards.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='boards.projectsettings'),
        ),
    ]
