# Generated by Django 3.2.4 on 2021-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teamRole',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('user', 'Пользователь')], max_length=100, verbose_name='Роль в команде'),
        ),
    ]
